---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- gem install minitest -v '~> 4.7' --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 1.9.3
- 2.0.0
env:
  - "YAML=syck"
  - "YAML=psych"
script: rake travis
matrix:
  exclude:
    - rvm: 2.0.0
      env: "YAML=syck"
