language: ruby
dist: trusty
sudo: required
branches:
  only:
    - master
    - staging
    - trying
    - /^[\d.]+$/
    - /.+-stable$/
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.2
  - ruby-head
env:
  - "TEST_TOOL=rubygems YAML=psych"
  - "TEST_TOOL=bundler RGV=master"
before_script:
  - util/ci before_script
script:
  - util/ci script
matrix:
  allow_failures:
    - rvm: ruby-head
      env: "TEST_TOOL=bundler RGV=master"
