language: ruby
dist: trusty
sudo: required
branches:
  only:
    - master
    - auto
    - /^[\d.]+$/
    - /.+-stable$/
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
env:
  - "TEST_TOOL=rubygems YAML=psych"
  - "TEST_TOOL=bundler RGV=master"
before_script:
  - util/ci before_script
script:
  - util/ci script
matrix:
  allow_failures:
    - rvm: 2.5.0
      env: "TEST_TOOL=rubygems YAML=psych"
    - rvm: ruby-head
