version: '{build}'
branches:
  only:
  - master
  - auto
  - /[\d.]+/
skip_tags: true
clone_depth: 10

environment:
  matrix:
  - ruby_version: 22
  - ruby_version: 22-x64
  - ruby_version: 23-x64
  - ruby_version: 24-x64
  - ruby_version: 25-x64
  - ruby_version: _trunk

init:
  - set PATH=C:/Ruby%ruby_version%/bin;C:/Program Files/7-Zip;C:/Program Files/AppVeyor/BuildAgent;C:/git/cmd;C:/Program Files (x86)/GNU/GnuPG/pub;C:/Windows/system32;C:\Windows;
  - mklink /d C:\git "C:\Program Files\Git"
  - set GIT=C:/git/cmd/git.exe
  - ps: >-
      if ($env:ruby_version -eq '_trunk') {
        $trunk_uri = 'https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z'
        (New-Object Net.WebClient).DownloadFile($trunk_uri, 'C:\ruby_trunk.7z')
        7z.exe x C:\ruby_trunk.7z -oC:\Ruby_trunk
      }

install:
- ps: >-
    git submodule update --init --recursive

    if ((gem query -i minitest) -eq $False){ gem install minitest --no-document }

    if ((gem query -i rake)     -eq $False){ gem install rake     --no-document }

test_script:
  - rake test

on_finish:
  - ruby -v

matrix:
  allow_failures:
    - ruby_version: _trunk

build: off
deploy: off
