name: daily-rubygems

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master
      - 3.2
      - vendor_uri

jobs:
  daily_rubygems:
    runs-on: ubuntu-18.04
    if: github.repository == 'rubygems/rubygems'
    strategy:
      matrix:
        ruby: [ ruby-head, truffleruby-head ]
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: Show Ruby version
        run: ruby --version

      - name: Test rubygems
        run: |
          rake setup
          rake test
    timeout-minutes: 60
