name: ruby-master

on: [push]

jobs:
  ruby_master:
    runs-on: ubuntu-latest
    container:
      image: rubylang/ruby:master-nightly-bionic
    strategy:
      matrix:
        test_tool: ["rubygems", "bundler"]
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: ruby -v
        run: ruby -v
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
      - name: Run Test
        run: util/ci.sh script
        env:
          TEST_TOOL: ${{ matrix.test_tool }}
