name: rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - reorg_workflows

jobs:
  rubygems:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, jruby-9.2.11.0 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Test
        run: |
          rake setup
          rake test
        shell: bash
    timeout-minutes: 60
