name: ubuntu-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - debugging_revert

jobs:
  ubuntu_bundler:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.4.9 ]
        rgv: [ v3.0.6 ]
    env:
      RGV: ${{ matrix.rgv }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
