name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - cache_test_times

jobs:
  windows_bundler:
    runs-on: windows-latest

    env:
      RGV: ..

    strategy:
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        shell: bash
      - name: Save test times to an artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_times
          path: bundler/tmp/parallel_runtime_rspec.log
